version: "3.7"

services:
  web:
    image: ghcr.io/ibz/usocial:master-buster
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - 8448:5000
    volumes:
      - ${LND_DATA_DIR}:/lnd:ro
      - ${APP_DATA_DIR}/data:/instance
    environment:
        USOCIAL_JOB: "WEB"
        LND_IP: "${LND_IP}"
        LND_GRPC_PORT: ${LND_GRPC_PORT}
        LND_DIR: "/lnd"
  fetcher:
    depends_on:
      - web
    image: ghcr.io/ibz/usocial:master-buster
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/instance
    environment:
        USOCIAL_JOB: "FETCH_FEEDS"
